### ISSUE TITLE
HTTPResponse' object has no attribute 'read_chunked'

### ISSUE THREAD

**Issue by tripledes** [kubevirt/ansible-kubevirt-modules#222]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Using:

```yaml
---
- hosts: localhost
  tasks:
    - name: Deploy CentOS 7 VM
      kubevirt_vm:
          state: running
          wait: true
          name: centosvm
          namespace: default
          memory: 1024M
          cloud_init_nocloud:
            userData: |-
              #cloud-config
              password: cloud
              chpasswd: { expire: False }
          disks:
            - name: containerdisk
              volume:
                persistentVolumeClaim:
                  claimName: pvc0090
              disk:
                bus: virtio
```

The VM/I were created but Ansible returned error:

```shell
[sup@sjr2 playbooks]$ ansible-playbook centos_vm.yml
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Deploy CentOS 7 VM] ************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'HTTPResponse' object has no attribute 'read_chunked'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "'HTTPResponse' object has no attribute 'read_chunked'"}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**What you expected to happen**:

Ansible to report changed = 1

**How to reproduce it (as minimally and precisely as possible)**:

Try to apply the above playbook

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.16.0
- Kubernetes version (use `kubectl version`): 1.12.4 (OCP4 Libvirt VMs)
- VM or VMI specifications:
- Cloud provider or hardware configuration: HW
- OS (e.g. from /etc/os-release): RHEL7
- Kernel (e.g. `uname -a`): 3.10
- Install tools: ansible 2.8.0b1
- Others:
