### ISSUE TITLE
delete object by name and namespace only

### ISSUE THREAD

**Issue by alexxa** [kubevirt/ansible-kubevirt-modules#41]
If one wants to delete an object, for example, a VM, only name and namespace should be required, nth else. 
ATM, 
```
    - name: Delete a VM
      kubevirt_vm:
        name: test-vm
        namespace: default
        state: absent

```
returns
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: pvc"}
```

and the VM is removed only when I specify `pvc`.
