### ISSUE TITLE
Check required status of modules options

### ISSUE THREAD

**Issue by alexxa** [kubevirt/ansible-kubevirt-modules#5]
As I understand from [kubevirt_*.py](https://github.com/kubevirt/ansible-kubevirt-modules/tree/master/library), there is no single required option. It can't be that way. At least `name` should be `"required": True.`

Then, if I run playbook similar to: 

```
  tasks:
    - kubevirt_vm:
       state: present
       name: my_vm
    - kubevirt_vm:
       state: absent
       name: my_other_vm
```

It always fails, because of 'missing namespace'. And so on.
